name: Sync OpenClaw Image to Aliyun ACR

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Aliyun ACR
        uses: docker/login-action@v4
        with:
          registry: crpi-cir91a122bvjkhqh.cn-shanghai.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Pull, Tag, and Push Image
        run: |
          OPENCLAW_VERSION="2026.5.19"      # 替换为目标具体版本号
          SOURCE_IMAGE="ghcr.io/openclaw/openclaw:${OPENCLAW_VERSION}"
          TARGET_IMAGE="crpi-cir91a122bvjkhqh.cn-shanghai.personal.cr.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/openclaw:latest"
          docker pull $SOURCE_IMAGE
          docker tag $SOURCE_IMAGE $TARGET_IMAGE
          docker push $TARGET_IMAGE
